document.write(5)
document.write('<br>')
document.write(7.3)
document.write('<br>')
document.write('poop')
document.write('<br>')
document.write('Poop' + 10)
document.write('<br>')
document.write(5 + 4.3)
document.write('<br>')
document.write(8.5 - 5.5)
document.write('<br>')
document.write(17 * 5)
document.write('<br>')
document.write(45 / 3.2)